# Generated by Django 4.2.1 on 2023-06-14 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("relations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendshiprelation",
            name="user1",
        ),
        migrations.RemoveField(
            model_name="friendshiprelation",
            name="user2",
        ),
        migrations.AddField(
            model_name="friendshiprelation",
            name="blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="friendshiprelation",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="friends", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="friendshiprelation",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blocked_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocked_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "block",
            },
        ),
    ]
