# Generated by Django 4.2.1 on 2023-06-15 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_date_of_birth_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blocks",
            field=models.ManyToManyField(
                default=None, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="friend_requests",
            field=models.ManyToManyField(
                default=None, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(
                default=None, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
