# Generated by Django 4.2.1 on 2023-06-15 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_blocks_alter_user_friend_requests_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="blocks",
            field=models.ManyToManyField(
                default=None, related_name="blocks", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="friend_requests",
            field=models.ManyToManyField(
                default=None,
                related_name="friend_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(
                default=None, related_name="friends", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
