# Generated by Django 4.2.1 on 2023-07-07 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="chat",
            table="chat",
        ),
        migrations.AlterModelTable(
            name="message",
            table="message",
        ),
    ]
